name: Go build/lint/test
on: [push, pull_request]
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build binary
        run: |
          make
      - name: Go test
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
