name: Go build/lint/test
on: [push, pull_request]
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          go get -t ./...
          go get golang.org/x/lint/golint
          go install golang.org/x/lint/golint
      - name: Build binary
        run: |
          make
      - name: Go Lint
        run: |
          golint -set_exit_status
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Disable errcheck (too noisy) for now.
          # TODO: improve this by disabling only problematic regexps.
          args: -D errcheck
      - name: Go test
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
